### ISSUE TITLE
Very helpful for me！

### ISSUE THREAD

**Issue by CoffeeDrinkRabbit** [Afoucaul/anki-autolearn#1]
Your project makes me rethink the possibility of anki's daily learning. At present, I will use your project when I need to carry out daily fragment learning. Of course, I still keep the main program of anki, so switching is not a problem, but I still want to come over and ask if there is any progress at present? For example, if you want to make an add-on, do you have the will in this regard?

**Comment by Afoucaul** [comment]
Hi @CoffeeDrinkRabbit , thanks for your feedback, this is truly warming!

This repo is already an add-on. It does require a feature that does not exist on the official version of Anki, but it is still a regular add-on.

If I remember correctly, my fork of Anki litterally adds only one line of code though, so it shouldn't be too hard to make a PR and have it accepted quite fast.
When this is done, you'll be able to install this add-on on your official version of Anki (once you've done an update I suppose).
Then I'll try to have this add-on accepted in the official add-on list.

I'm glad what I've done is helpful to you; it makes me feel more confident that a PR on Anki is worthwhile.
I'll give it a shot, and will let you know when this is complete!

**Comment by Afoucaul** [comment]
@CoffeeDrinkRabbit I just opened a PR on the official Anki repo: https://github.com/dae/anki/pull/358
Hope this can be merged soon!

**Comment by Afoucaul** [comment]
Hey @CoffeeDrinkRabbit , I came up with a solution to make this add-on work without any changes on Anki's official source.
I just pushed my changes.
Would you mind giving it a try on your non-modified version?

Thanks in advance!

**Comment by CoffeeDrinkRabbit** [comment]
Can't wait to use this!!!

**Comment by CoffeeDrinkRabbit** [comment]
I've overwritten the previous add-on file on the standard anki,but It doesn't work for me.

my Anki version : 2.1.15 (442df9d6)

Qt 5.12.1 PyQt 5.11.3

**Comment by Afoucaul** [comment]
Do you have other add-ons installed?

**Comment by CoffeeDrinkRabbit** [comment]
I tried to turn all the other add on off, but nothing changed

**Comment by Afoucaul** [comment]
That's weird, I can't understand why this does not work. Let me investigate the issue, I'll let you know ASAP!

**Comment by CoffeeDrinkRabbit** [comment]
I changed another computer and found it working well

**Comment by Afoucaul** [comment]
That's nice to read! It might be that you have not properly removed the reference to the old add-on on your first computer.

I'm closing this issue since it seems to work now, but please let me know when you manage to make it work on that first computer, and feel free to open an issue if you want some features!

**Comment by CoffeeDrinkRabbit** [comment]
After I reinstalled anki on the previous computer, your add-on works well！
